[package]
name = "blocks_iterator"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.26.0"
structopt = "0.3.21"
log = "0.4.11"
env_logger = "0.7"
glob = "0.3.0"
fxhash = "0.2.1" # hashmap slighlty faster than std with non crypto-secure hashing algo