[package]
name = "blocks_iterator"
version = "0.2.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
edition = "2018"
description = "Iterates Bitcoin blocks"
repository = "https://github.com/RCasatta/blocks_iterator"
documentation = "https://docs.rs/blocks_iterator/"
keywords = ["bitcoin", "blocks", "iterate"]
readme = "Readme.md"
license = "MIT"

[dependencies]
bitcoin = "0.26.1"
structopt = "0.3.21"
log = "0.4.11"
env_logger = "0.7"
glob = "0.3.0"
fxhash = "0.2.1"
rayon = { version = "1.5.0", optional = true }
bitcoinconsensus = { version = "0.19.0-3", optional = true }

[features]
verify = ["bitcoin/bitcoinconsensus", "rayon", "bitcoinconsensus"]

[[example]]
name = "heaviest"

[[example]]
name = "iterate"

[[example]]
name = "most_output"

[[example]]
name = "verify"
required-features = ["verify"]
