name: blocks-iterator

on: [pull_request]

jobs:

  cosmetics:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy
      - name: fmt
        run: cargo fmt -- --check
      - name: clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly, 1.51.0]

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
        with:
          key: ${{ matrix.rust }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args:  --verbose
      - run: cargo +nightly bench --features unstable
        if: ${{ matrix.rust == 'nightly' }}

  examples:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        example: [ "verify --features verify", "signatures_in_witness", "outputs_versions"]
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
        with:
          key: ${{ matrix.example }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        env:
          RUST_LOG: "debug"
        with:
          command: run
          args: --example ${{ matrix.example }} -- --blocks-dir blocks --network testnet

  pipe-example:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
        with:
          key: ${{ matrix.example }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --examples
      - run: ./target/release/blocks_iterator --blocks-dir blocks --network testnet --max-reorg 40 | ./target/release/examples/most_output_pipe | ./target/release/examples/heaviest_pipe >/dev/null
