name: blocks-iterator

on: [push, pull_request]

jobs:

  cosmetics:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy
      - name: fmt
        run: cargo fmt -- --check
      - name: clippy
        run: cargo clippy -- -D warnings

  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly, 1.41.0, 1.42.0, 1.43.0, 1.44.0, 1.45.0, 1.46.0]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args:  --verbose --all

  examples:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        example: [ "heaviest", "iterate", "most_output", "verify --features verify", "signatures_in_witness", "outputs_versions"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --example ${{ matrix.example }}
